2017-05-04 14:30:33,473 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869279865616
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4877, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 14:30:36,893 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869284457424
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4877, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 14:30:38,917 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869283672784
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4877, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 14:30:39,182 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869283773840
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4877, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 14:34:13,788 :: ERROR :: Exception at http://localhost:6543/user/register
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869286907600
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 153, in user_register
    if not form['user_name'] or not form['user_password']:
KeyError: 'user_name'
2017-05-04 14:34:52,993 :: ERROR :: Exception at http://localhost:6543/user/register
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869287565008
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 164, in user_register
    'laboratory': form['laboratory'],
KeyError: 'laboratory'
2017-05-04 14:34:55,873 :: ERROR :: Exception at http://localhost:6543/user/register
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869287083216
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 164, in user_register
    'laboratory': form['laboratory'],
KeyError: 'laboratory'
2017-05-04 14:36:01,255 :: ERROR :: Exception at http://localhost:6543/user/register
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869286851664
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 164, in user_register
    'laboratory': form['laboratory'],
KeyError: 'laboratory'
2017-05-04 14:36:24,022 :: ERROR :: Exception at http://localhost:6543/user/register
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e51bbd93565461163405&tb=139869288106576
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 165, in user_register
    'country': form['country'],
KeyError: 'country'
2017-05-04 15:05:39,604 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=7d42bdf603630bd510f7&tb=140649643965712
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4883, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 15:11:45,054 :: ERROR :: Exception at http://localhost:6543/user/register
traceback url: http://localhost:6543/_debug_toolbar/exception?token=b7ba0da66b55eb93d7cd&tb=140498079998672
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 153, in user_register
    if not form['user_name'] or not form['user_password']:
KeyError: 'user_name'
2017-05-04 15:13:20,014 :: ERROR :: Exception at http://localhost:6543/user/register
traceback url: http://localhost:6543/_debug_toolbar/exception?token=5fc71be542db66ae94cb&tb=139823132930192
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 162, in user_register
    'first_name': form['first_name'],
KeyError: 'first_name'
2017-05-04 15:14:56,633 :: ERROR :: Exception at http://localhost:6543/user/register
traceback url: http://localhost:6543/_debug_toolbar/exception?token=f3eaab5052aff1b099d1&tb=140664446971536
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 153, in user_register
    if not form['user_name'] or not form['user_password']:
KeyError: 'user_password'
2017-05-04 15:16:02,315 :: ERROR :: Exception at http://localhost:6543/user/confirm_email
traceback url: http://localhost:6543/_debug_toolbar/exception?token=b59cece2213634ba121f&tb=139696429146384
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 213, in confirm_email
    return {'msg': alert_register, 'status':'success'}
NameError: global name 'alert_register' is not defined
2017-05-04 15:21:08,341 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e7711bcae53ffad04c26&tb=140671490144464
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4883, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 15:21:10,083 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e7711bcae53ffad04c26&tb=140671489448720
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4883, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 15:22:24,665 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e7711bcae53ffad04c26&tb=140671479048400
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4883, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 15:22:24,861 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e7711bcae53ffad04c26&tb=140671477322384
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4883, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 15:22:26,934 :: ERROR :: Exception at http://localhost:6543/user/recover
traceback url: http://localhost:6543/_debug_toolbar/exception?token=e7711bcae53ffad04c26&tb=140671475468112
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4883, in user_recover
    if form['user_name'] is None:
KeyError: 'user_name'
2017-05-04 15:27:41,038 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJGtyT3k3TEhSOVJkQkxPTFdkNXZhLy5rZ0xHSWNZSlA3bUs0SnpmR3FXR042enkwNGpQRTZLIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImNsZW1lbnQubGFuY2llbkBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQwNDU5LCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.AOay_CBAfORAVfRkR0d7bY83GLRBXnDMDA2atUHCOMY
2017-05-04 15:29:05,224 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/password_recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJGtyT3k3TEhSOVJkQkxPTFdkNXZhLy5rZ0xHSWNZSlA3bUs0SnpmR3FXR042enkwNGpQRTZLIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImNsZW1lbnQubGFuY2llbkBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQwNTQzLCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.VaToGcIxiCSoP08T-GWjQQ6OtaNZmuGHapgYvOy0PzI
2017-05-04 15:32:29,408 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/password_recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJExWazJtRThqcTJzdTBTTFZFR2c2aC5tUjQ1cmI2Qi9QbFdkVkRBOVRpd01DTWw1b3R2aHlDIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImNsZW1lbnQubGFuY2llbkBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQwNzQ4LCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.ucUxW9nyScVh0oAPb9vMvgRNp0yQPWIWecF7h6rs2fc
2017-05-04 15:34:23,176 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/password_recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJEZIWFNJQWNZQXhJMWgzVnF0b2tyZk9MZUc2ejBHZ1BTZWNaU0UzSnVxLnBSdmJOSzBBUUZLIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImNsZW1lbnQubGFuY2llbkBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQwODYxLCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.cJyxCEoEn3u8cD5RumEiFi8PY_ZkYR37PjzYqRYacfo
2017-05-04 15:34:47,216 :: ERROR :: Exception at http://localhost:6543/user/login
traceback url: http://localhost:6543/_debug_toolbar/exception?token=145ec6669b77e6636c69&tb=139862959790608
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4903, in login
    user_in_db = request.registry.db_mongo['users'].find_one({'id': form['user_name']})
KeyError: 'user_name'
2017-05-04 15:34:52,112 :: ERROR :: Exception at http://localhost:6543/user/login
traceback url: http://localhost:6543/_debug_toolbar/exception?token=145ec6669b77e6636c69&tb=139862957279632
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4903, in login
    user_in_db = request.registry.db_mongo['users'].find_one({'id': form['user_name']})
KeyError: 'user_name'
2017-05-04 15:34:53,930 :: ERROR :: Exception at http://localhost:6543/user/login
traceback url: http://localhost:6543/_debug_toolbar/exception?token=145ec6669b77e6636c69&tb=139862955491984
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4903, in login
    user_in_db = request.registry.db_mongo['users'].find_one({'id': form['user_name']})
KeyError: 'user_name'
2017-05-04 15:34:54,681 :: ERROR :: Exception at http://localhost:6543/user/login
traceback url: http://localhost:6543/_debug_toolbar/exception?token=145ec6669b77e6636c69&tb=139862957233104
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4903, in login
    user_in_db = request.registry.db_mongo['users'].find_one({'id': form['user_name']})
KeyError: 'user_name'
2017-05-04 15:34:55,177 :: ERROR :: Exception at http://localhost:6543/user/login
traceback url: http://localhost:6543/_debug_toolbar/exception?token=145ec6669b77e6636c69&tb=139862951815888
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4903, in login
    user_in_db = request.registry.db_mongo['users'].find_one({'id': form['user_name']})
KeyError: 'user_name'
2017-05-04 15:39:58,129 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/password_recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJGhoeGFtbS4zZnRjaVRJVmdQOHpMTnVvbFZxek5IdHh0bUVDT1p0a1RUdThHbUdYeVJaRmVpIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImNsZW1lbnQubGFuY2llbkBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQxMTk2LCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.ADju5ANPfF7Me5U3gxJVpbecfqq46NlyMcvjDprt7dY
2017-05-04 16:55:24,750 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/password_recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJDhxMGhLU3AxcFpaa3U0Y212TUNIN09ZZnhQWWI2NW9sSThqL2dWdTJkbml6NWxnU3J2VjZxIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImNsZW1lbnQubGFuY2llbkBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQ1NzIyLCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.2w31aGmBrTjnNzYt_BL1Xb5QnrBTfrQXpAyMgBQ1STo
2017-05-04 16:55:35,706 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/password_recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJGlaYmh6alJKUnVYcXFQOUhVMkRGeXVVaUxhbHo1UHZxd00vSGtSUS9lbENmcVg0YVo2dG0yIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImdlbmV1bGlrZUBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQ1NzM0LCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.yz00lJkaH64zTwgiiGXdRgd4bvuww-WJG-IJnEQ89Dw
2017-05-04 17:19:16,817 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/password_recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJDhxMGhLU3AxcFpaa3U0Y212TUNIN09ZZnhQWWI2NW9sSThqL2dWdTJkbml6NWxnU3J2VjZxIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImNsZW1lbnQubGFuY2llbkBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQ3MTU1LCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.-MzNyBZ4wcNqh83bIE0o8k5LduueTbsEkHky9ddsNgw
2017-05-04 17:19:34,285 :: INFO :: You requested a password reset, please click on following link to reset your password:
http://localhost:6543/app/index.html#/password_recover?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InN0YXR1cyI6ImFwcHJvdmVkIiwiZmlyc3RfbmFtZSI6IkNsZW1lbnQiLCJsYXN0X25hbWUiOiJMYW5jaWVuIiwic2VsZWN0ZWRJRCI6IiIsInBhc3N3b3JkIjoiJDJiJDEyJGo1MGZBak5PYjl0Mzh3M0RndVRlZC4ucDR4VkQ2SUFoQXVzTXQ2eE9tbVNxVjg4TEt0Qi8yIiwiYXZhdGFyIjoiIiwiYWRkcmVzcyI6Ik5vIGFkZHJlc3MiLCJsYWJvcmF0b3J5IjpudWxsLCJpZCI6ImdlbmV1bGlrZUBnbWFpbC5jb20ifSwiZXhwIjoxNDkzOTQ3MTcyLCJhdWQiOiJ1cm46Z2VuZXVsaWtlL3JlY292ZXIifQ.rMJ2EUyShgiv1Cy3wEV5amuxDKJuzRqGyqDDhIhxcGQ
2017-05-05 11:47:52,414 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=ce03fea00536bc2d9a00&tb=140320567536912
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4932, in login
    request.registry.db_mongo['users'].update({'id': user_id},{'$set': {'lastseen': datetime.datetime.now()}})
NameError: global name 'user_id' is not defined
2017-05-05 11:47:54,911 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=ce03fea00536bc2d9a00&tb=140320541285520
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4932, in login
    request.registry.db_mongo['users'].update({'id': user_id},{'$set': {'lastseen': datetime.datetime.now()}})
NameError: global name 'user_id' is not defined
2017-05-05 11:48:08,229 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=ce03fea00536bc2d9a00&tb=140320541357392
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4932, in login
    request.registry.db_mongo['users'].update({'id': user_id},{'$set': {'lastseen': datetime.datetime.now()}})
NameError: global name 'user_id' is not defined
2017-05-05 11:50:25,346 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=261049d2585d2506b313&tb=140569030997584
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 127, in user_info
    "adress":user_in_db['adress'],
KeyError: 'adress'
2017-05-05 11:51:27,608 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=eec15a159c77f81e3682&tb=139989694408592
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":str(user_in_db['last_seen']-datetime.datetime.now())
KeyError: 'last_seen'
2017-05-05 13:11:53,527 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=3fa4d37b3650a7822090&tb=139768218432144
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4934, in login
    'aud': 'urn:geneulike/api'}, secret)
  File "build/bdist.linux-x86_64/egg/jwt/api_jwt.py", line 52, in encode
    cls=json_encoder
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 5, 5, 13, 11, 1, 351000) is not JSON serializable
2017-05-05 13:11:56,810 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=3fa4d37b3650a7822090&tb=139768216254928
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4934, in login
    'aud': 'urn:geneulike/api'}, secret)
  File "build/bdist.linux-x86_64/egg/jwt/api_jwt.py", line 52, in encode
    cls=json_encoder
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 5, 5, 13, 11, 53, 522000) is not JSON serializable
2017-05-05 13:11:58,040 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=3fa4d37b3650a7822090&tb=139768216255312
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4934, in login
    'aud': 'urn:geneulike/api'}, secret)
  File "build/bdist.linux-x86_64/egg/jwt/api_jwt.py", line 52, in encode
    cls=json_encoder
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 5, 5, 13, 11, 56, 806000) is not JSON serializable
2017-05-05 13:15:34,458 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=ca0d96a8ebd02e4804de&tb=139732843940240
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4934, in login
    'aud': 'urn:geneulike/api'}, secret)
  File "build/bdist.linux-x86_64/egg/jwt/api_jwt.py", line 52, in encode
    cls=json_encoder
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2017, 5, 5, 13, 11, 58, 36000) is not JSON serializable
2017-05-05 13:20:37,507 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=ca3327246d0925007e54&tb=140185391198160
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":str(user_in_db['last_seen']-datetime.datetime.now())
TypeError: unsupported operand type(s) for -: 'unicode' and 'datetime.datetime'
2017-05-05 13:21:29,938 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=ca3327246d0925007e54&tb=140185344703568
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":str(user_in_db['last_seen']-datetime.datetime.now())
TypeError: unsupported operand type(s) for -: 'unicode' and 'datetime.datetime'
2017-05-05 13:39:46,089 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=933c8d5086bc59dc7c53&tb=140478653964944
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 145, in getLastSeen
    day=int(time.split("\s")[0].split("-")[2])
ValueError: invalid literal for int() with base 10: '05 13:39:43.602616'
2017-05-05 13:42:29,431 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=1d789b6e0ed330436a07&tb=140381341354192
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 152, in getLastSeen
    if(year < int(dateNow.year()) and int(dateNow.year()) - year == 1):
TypeError: 'int' object is not callable
2017-05-05 13:44:24,660 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=6fe005589227963d4b03&tb=139840105224400
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 152, in getLastSeen
    if(year < dateNow.year() and dateNow.year() - year == 1):
TypeError: 'int' object is not callable
2017-05-05 13:45:07,684 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=8c62ae183470d095a907&tb=139855830272144
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 151, in getLastSeen
    return str(dateNow.year())
TypeError: 'int' object is not callable
2017-05-05 13:45:35,872 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=24a38487c9c0a937a81d&tb=140539912906640
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 151, in getLastSeen
    return dateNow.year()
TypeError: 'int' object is not callable
2017-05-05 13:46:19,161 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=2e9e569d9448458be3c3&tb=140592713705552
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 151, in getLastSeen
    return datetime.datetime.now().year()
TypeError: 'int' object is not callable
2017-05-05 13:50:36,496 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=b5dae86931cfed0ac7dc&tb=140400890891024
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 173, in getLastSeen
    elif(seconde < dateNow.seconde and dateNow.seconde - seconde == 1):
NameError: global name 'seconde' is not defined
2017-05-05 13:52:20,235 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=40187867d79833b7745d&tb=139903941128656
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 173, in getLastSeen
    elif(seconde < dateNow.second and dateNow.second - second == 1):
NameError: global name 'seconde' is not defined
2017-05-05 14:32:05,347 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=3683801c8cfe71956093&tb=139639463360336
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getTimeConnected(user_in_db['connected']),
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getTimeConnected
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 14:34:33,663 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=ed6b5db8343cc2fdf98c&tb=140219944544784
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "last_seen":getLastSeen(user_in_db['last_seen'])
KeyError: 'last_seen'
2017-05-05 14:40:26,204 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=50c7c0a08c338e42eb87&tb=140007886018064
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 14:53:25,173 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=44dda80a2ab474713227&tb=139933890603920
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 14:53:58,827 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=44dda80a2ab474713227&tb=139933878289104
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 14:54:04,291 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=44dda80a2ab474713227&tb=139933874217616
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 14:55:04,930 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=44dda80a2ab474713227&tb=139933884803856
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 14:55:31,782 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=44dda80a2ab474713227&tb=139933886994000
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 14:59:08,568 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=4e90792e1dbc267d8787&tb=140677113323600
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
KeyError: 'connected'
2017-05-05 15:00:55,303 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=52630c7e74fdff4f111a&tb=140616416148880
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 15:02:18,878 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=52630c7e74fdff4f111a&tb=140616411565008
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 15:02:55,794 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=65388c747935f46232b3&tb=140650068446096
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 15:03:23,437 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=65388c747935f46232b3&tb=140650060489616
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 146, in getLastSeen
    hour=int(time.split(" ")[1].split(":")[0])
IndexError: list index out of range
2017-05-05 15:08:15,032 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=2835473cbf438a3e691f&tb=140332949683408
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 143, in getLastSeen
    return str(time.split(" ")[0].split("-")[1])
IndexError: list index out of range
2017-05-05 15:11:23,815 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=ebbf5e5c17cf25104f5d&tb=140108007464784
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 176, in getLastSeen
    return str(dateNow.second - second) + " seconds ago"
TypeError: unsupported operand type(s) for -: 'int' and 'unicode'
2017-05-05 15:19:21,240 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=23556d81436fab7b08f7&tb=140361357524304
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 148, in getLastSeen
    second=int((time.split(" ")[1])[6:9])
ValueError: invalid literal for int() with base 10: '02.'
2017-05-05 15:20:22,828 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=0c91e8f3bc7abe07b749&tb=139804376275920
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int((time.split(" ")[0])[5:7])
ValueError: invalid literal for int() with base 10: ''
2017-05-05 15:21:17,520 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=4fbdd3b82a782535ee43&tb=140652464807248
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 144, in getLastSeen
    month=int((time.split(" ")[0])[5:7])
ValueError: invalid literal for int() with base 10: ''
2017-05-05 15:26:24,308 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=7dfb22f63cc105d8805c&tb=140703356673488
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 143, in getLastSeen
    return int(time[16:17])
ValueError: invalid literal for int() with base 10: ':'
2017-05-05 15:26:39,752 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=7dfb22f63cc105d8805c&tb=140703352166160
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 143, in getLastSeen
    return int(time[16:17])
ValueError: invalid literal for int() with base 10: ':'
2017-05-05 15:29:52,448 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=8a591ef534eaefcb74ce&tb=140564972576208
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 133, in user_info
    "joined": user_in_db['joined'].date,
AttributeError: 'unicode' object has no attribute 'date'
2017-05-05 15:31:04,423 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=d69636c3ed9b5774d112&tb=140664266669392
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4975, in login
    request.registry.db_mongo['users'].update({'id': form['user_name']},{'$set': {'connected': {datetime.datetime.now()} }})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: set([datetime.datetime(2017, 5, 5, 15, 31, 4, 420601)])
2017-05-05 15:31:07,072 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=d69636c3ed9b5774d112&tb=140664263657936
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4975, in login
    request.registry.db_mongo['users'].update({'id': form['user_name']},{'$set': {'connected': {datetime.datetime.now()} }})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: set([datetime.datetime(2017, 5, 5, 15, 31, 7, 69929)])
2017-05-05 15:32:33,130 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=43129f9ff905493da9d2&tb=140364331981200
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4975, in login
    request.registry.db_mongo['users'].update({'id': form['user_name']},{'$set': {'connected': {datetime.datetime.now()} }})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: set([datetime.datetime(2017, 5, 5, 15, 32, 33, 128127)])
2017-05-05 15:32:38,938 :: ERROR :: Exception at http://0.0.0.0:6543/user/login
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=43129f9ff905493da9d2&tb=140364328924560
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4975, in login
    request.registry.db_mongo['users'].update({'id': form['user_name']},{'$set': {'connected': {datetime.datetime.now()} }})
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 551, in update
    docs, check_keys, self.uuid_subtype, client)
InvalidDocument: Cannot encode object: set([datetime.datetime(2017, 5, 5, 15, 32, 38, 936295)])
2017-05-05 15:38:27,761 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=51b105cf8faf5f92a712&tb=139665343579088
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 143, in getLastSeen
    year=int(time[0:4])
ValueError: invalid literal for int() with base 10: '5 mi'
2017-05-05 15:41:15,350 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=a93e108d86b204adea29&tb=140682862135568
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getlastSeen(user_in_db['connected'])
NameError: global name 'getlastSeen' is not defined
2017-05-05 15:41:29,761 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=a93e108d86b204adea29&tb=140682649070288
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getlastSeen(user_in_db['connected'])
NameError: global name 'getlastSeen' is not defined
2017-05-05 15:42:02,443 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=a93e108d86b204adea29&tb=140682645592272
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getlastSeen(user_in_db['connected'])
NameError: global name 'getlastSeen' is not defined
2017-05-05 15:42:35,584 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=4a24f9f32cf3184cb834&tb=140709706303824
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getlastSeen(user_in_db['connected'])
NameError: global name 'getlastSeen' is not defined
2017-05-05 15:44:02,228 :: ERROR :: Exception at http://0.0.0.0:6543/user/clement.lancien@gmail.com
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=84fca48a08cb4120164f&tb=139668777403216
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 138, in user_info
    "connected":getLastSeen(user_in_db['connected'])
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 143, in getLastSeen
    year=int(time[0:4])
ValueError: invalid literal for int() with base 10: '1 mi'
2017-05-05 16:41:46,279 :: ERROR :: Exception at http://0.0.0.0:6543/dataset_download/templates/TOXsIgN_template_v0.4.xlsx
traceback url: http://0.0.0.0:6543/_debug_toolbar/exception?token=088c22a131a2ccc58902&tb=140215299295632
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 409, in viewresult_to_response
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 730, in file_dataset
    url_file = os.path.join(request.registry.dataset_path,directory,downfile)
AttributeError: 'Registry' object has no attribute 'dataset_path'
2017-05-16 13:31:54,403 :: DEBUG :: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2017-05-16 13:31:57,578 :: DEBUG :: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
2017-05-16 13:31:57,579 :: DEBUG :: Starting new HTTP connection (2): localhost
2017-05-16 13:32:04,432 :: WARNING :: GET http://localhost:9200/geneulike/_search?search_type=query_then_fetch&size=1000 [status:N/A request:10.028s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 95, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/util/retry.py", line 324, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10)
2017-05-16 13:32:04,727 :: DEBUG :: > {"query": {"query_string": {"query": "status:public AND _all:undefined*", "default_operator": "AND", "analyzer": "standard"}}}
2017-05-16 13:32:04,730 :: ERROR :: Exception at http://localhost:6543/search
traceback url: http://localhost:6543/_debug_toolbar/exception?token=0cf44b7774a955a07948&tb=140227980917520
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4916, in search
    body =  {"query" : { "query_string" : {"query" :request_query,"default_operator":"AND",'analyzer': "standard"}}})
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 539, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 103, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10))
2017-05-16 13:32:07,590 :: WARNING :: GET http://localhost:9200/geneulike/_search?search_type=query_then_fetch&size=1000 [status:N/A request:10.012s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 95, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/util/retry.py", line 324, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3-1.20-py2.7.egg/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
ReadTimeoutError: HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10)
2017-05-16 13:32:07,591 :: DEBUG :: > {"query": {"query_string": {"query": "status:public AND _all:a*", "default_operator": "AND", "analyzer": "standard"}}}
2017-05-16 13:32:07,593 :: ERROR :: Exception at http://localhost:6543/search
traceback url: http://localhost:6543/_debug_toolbar/exception?token=0cf44b7774a955a07948&tb=140227992193616
Traceback (most recent call last):
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/toolbar.py", line 215, in toolbar_tween
    response = _handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/home/clancien/.local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/clancien/Desktop/site/geneulike/geneulike/views.py", line 4916, in search
    body =  {"query" : { "query_string" : {"query" :request_query,"default_operator":"AND",'analyzer': "standard"}}})
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 539, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 103, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=u'localhost', port=9200): Read timed out. (read timeout=10))
